<a href="https://colab.research.google.com/github/jiriyaporn/data_viz/blob/main/More_advanced_data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ที่เรียนไปแล้ว 1 ตัวคือ list หน้าตาแบบนี้

list เก็บได้ทั้งแบบ string number

# Dictionary

สามารถ index ด้วยอะไรก็ได้ แต่ลำดับจะหายไป 

In [ ]:
ex_dict = {' a ' : 10, '1':1, 'stat' :5} # curly brackets ในการบอก dict

In [ ]:
ex_dict['stat']

5

In [ ]:
ex2_dict = {1: 'one', 2 : 'two', 3 : 'three'}

In [ ]:
ex2_dict[2]

'two'

##การเพิ่มสมาชิกใน dict

In [ ]:
ex2_dict[0] = 'zero'

คำสั่งพิเศษที่ใช้

In [ ]:
ex2_dict.keys()


dict_keys([1, 2, 3, 0])

In [ ]:
for index in ex2_dict.keys() :
  print(index)

1
2
3
0


In [ ]:
ex2_dict.values()



dict_values(['one', 'two', 'three', 'zero'])

เอาไปใช้ร่วมกับ dataframe ของ pandas

# Number Arrey  (arrey n มิติ)

numpy คือ package ที่ทำงานเกี่ยวกับ arrey ของตัวเลข (มีคนเขียนแล้ว)

numpy > number python

In [ ]:
import numpy #วิธีเรียกใช้งาน

In [ ]:
ex_2d_array = numpy.array([[5.2, 3.0, 4.5],[9.1, 0.1, 0.3]])

print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


#การชี้ค่าใน numpy array

In [ ]:
ex_2d_array[1,2]

0.3

In [ ]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]] #การมี list

print(len(list_x))

print(list_x[1])

print(list_x[1][2])

2
[9.1, 0.1, 0.3]
0.3


Operations

In [ ]:
ex_2d_array = numpy.array([[1,0,0],[0,0,1]])
print(ex_2d_array)
print(ex_2d_array)

[[1 0 0]
 [0 0 1]]
[[1 0 0]
 [0 0 1]]


In [ ]:
ex_2d_array.shape #ตรวจสอบขนาดของ matrix

(2, 3)

In [ ]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]] #การมี list
list_x2 = [[1,0,0],[0,0,1]] 
list_x + list_x2

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3], [1, 0, 0], [0, 0, 1]]

In [ ]:
ex_2d_array - ex_2d_array

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
ex_2d_array * ex_2d_array #เอาตำแหน่งเดียวกันมาคูณกัน

array([[1, 0, 0],
       [0, 0, 1]])

In [ ]:
print(ex_2d_array)
print(ex_2d_array.T)

[[1 0 0]
 [0 0 1]]
[[1 0]
 [0 0]
 [0 1]]


In [ ]:
dot_mat = numpy.dot(ex_2d_array,ex_2d_array.T)
print(dot_mat)


[[1 0]
 [0 1]]


In [ ]:
numpy.linalg.det(dot_mat)

1.0

## matrix slicing

In [ ]:
print(ex_2d_array)

[[1 0 0]
 [0 0 1]]


In [ ]:
ex_2d_array[1,1:]

array([0, 1])

In [ ]:
ex_2d_array[:,:2]

array([[1, 0],
       [0, 0]])

## random,ones,zeros

## HW5 

เขียนฟังก์ชัน * เมทริกซ์ 

แล้ว test กับ matrix 

(2,3)*(3,2)

(4,4)*(4,1)

(2,2)*(2,2)

In [1]:
import numpy as np

In [11]:
# (2,3)
mat_1 = np.array([[1,2,3],[2,3,5]])
mat_1 


array([[1, 2, 3],
       [2, 3, 5]])

In [5]:
# (3,2)
mat_2 = np.array([[2,3],[2,5],[6,2]])
mat_2


array([[2, 3],
       [2, 5],
       [6, 2]])

In [34]:
# (4,4)
mat_3 = np.array([[2,3,5,4], [1,3,2,5], [3,2,6,2], [2,1,2,3]])
mat_3

array([[2, 3, 5, 4],
       [1, 3, 2, 5],
       [3, 2, 6, 2],
       [2, 1, 2, 3]])

In [35]:
# (4,1)
mat_4 = np.array([[2], [1], [3], [5]])
mat_4

array([[2],
       [1],
       [3],
       [5]])

In [36]:
# (2,2)
mat_5 = np.array([[2,6], [4,5]])
mat_5

array([[2, 6],
       [4, 5]])

In [37]:
# (2,2)
mat_6 = np.array([[8,4], [8,3]])
mat_6

array([[8, 4],
       [8, 3]])

In [21]:
def mul_mat(a, b) :
  c = [[0 for row in range(len(b[0]))] for col in range(len(a))]
  for i in range(len(a)) :
    for j in range(len(b[0])) :
      for k in range(len(b)) :
        c[i][j] += a[i][k]*b[k][j]
  r = np.matrix(c)
  return r 

In [22]:
mul_mat(mat_1,mat_2) #(2,3)*(3,2)

matrix([[24, 19],
        [40, 31]])

In [38]:
mul_mat(mat_3,mat_4) #(4,4)*(4,1)

matrix([[42],
        [36],
        [36],
        [26]])

In [39]:
mul_mat(mat_5,mat_6) #(2,2)*(2,2)

matrix([[64, 26],
        [72, 31]])

#ตรวจสอบใช้ np.dot

In [40]:
np.dot(mat_1,mat_2)

array([[24, 19],
       [40, 31]])