<a href="https://colab.research.google.com/github/jiriyaporn/data_viz/blob/main/More_advanced_data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ที่เรียนไปแล้ว 1 ตัวคือ list หน้าตาแบบนี้

list เก็บได้ทั้งแบบ string number

# Dictionary

สามารถ index ด้วยอะไรก็ได้ แต่ลำดับจะหายไป 

In [2]:
ex_dict = {' a ' : 10, '1':1, 'stat' :5} # curly brackets ในการบอก dict

In [3]:
ex_dict['stat']

5

In [6]:
ex2_dict = {1: 'one', 2 : 'two', 3 : 'three'}

In [7]:
ex2_dict[2]

'two'

##การเพิ่มสมาชิกใน dict

In [8]:
ex2_dict[0] = 'zero'

คำสั่งพิเศษที่ใช้

In [23]:
ex2_dict.keys()


dict_keys([1, 2, 3, 0])

In [24]:
for index in ex2_dict.keys() :
  print(index)

1
2
3
0


In [22]:
ex2_dict.values()



dict_values(['one', 'two', 'three', 'zero'])

เอาไปใช้ร่วมกับ dataframe ของ pandas

# Number Arrey  (arrey n มิติ)

numpy คือ package ที่ทำงานเกี่ยวกับ arrey ของตัวเลข (มีคนเขียนแล้ว)

numpy > number python

In [80]:
import numpy #วิธีเรียกใช้งาน

In [85]:
ex_2d_array = numpy.array([[5.2, 3.0, 4.5],[9.1, 0.1, 0.3]])

print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


#การชี้ค่าใน numpy array

In [86]:
ex_2d_array[1,2]

0.3

In [42]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]] #การมี list

print(len(list_x))

print(list_x[1])

print(list_x[1][2])

2
[9.1, 0.1, 0.3]
0.3


Operations

In [88]:
ex_2d_array = numpy.array([[1,0,0],[0,0,1]])
print(ex_2d_array)
print(ex_2d_array)

[[1 0 0]
 [0 0 1]]
[[1 0 0]
 [0 0 1]]


In [89]:
ex_2d_array.shape #ตรวจสอบขนาดของ matrix

(2, 3)

In [71]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]] #การมี list
list_x2 = [[1,0,0],[0,0,1]] 
list_x + list_x2

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3], [1, 0, 0], [0, 0, 1]]

In [90]:
ex_2d_array - ex_2d_array

array([[0, 0, 0],
       [0, 0, 0]])

In [91]:
ex_2d_array * ex_2d_array #เอาตำแหน่งเดียวกันมาคูณกัน

array([[1, 0, 0],
       [0, 0, 1]])

In [92]:
print(ex_2d_array)
print(ex_2d_array.T)

[[1 0 0]
 [0 0 1]]
[[1 0]
 [0 0]
 [0 1]]


In [104]:
dot_mat = numpy.dot(ex_2d_array,ex2_2d_array.T)
print(dot_mat)


NameError: ignored

In [103]:
numpy.linalg.det(dot_mat)

NameError: ignored

## matrix slicing

In [97]:
print(ex_2d_array)

[[1 0 0]
 [0 0 1]]


In [98]:
ex_2d_array[1,1:]

array([0, 1])

In [99]:
ex_2d_array[:,:2]

array([[1, 0],
       [0, 0]])

## random,ones,zeros

## HW5 

เขียนฟังก์ชัน * เมทริกซ์ 

แล้ว test กับ matrix 

(2,3)*(3,2)

(4,4)*(4,1)

(2,2)*(2,2)